# This is a Snakemake workflow definition file.
# See:
# https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html

rule echo:
    conda: "envs/env.yaml"
    # Show NumPy package version
    shell: "printf 'numpy ' && python -c 'import numpy; print(numpy.__version__)'"
